export enum actionTypes {
  // Google Maps API & Autocomplete
  LOAD_GOOGLE_PLACES_API = 'LOAD_GOOGLE_PLACES_API',
  FETCH_AUTOCOMPLETE = 'FETCH_AUTOCOMPLETE',
  UPDATE_PREDICTIONS = 'UPDATE_PREDICTIONS',
  CLEAR_PREDICTIONS = 'CLEAR_PREDICTIONS',

  // Location Field
  UPDATE_LOCATION_FIELD_VALUE = 'UPDATE_LOCATION_FIELD_VALUE',
  CLEAR_LOCATION_FIELD_VALUE = 'CLEAR_LOCATION_FIELD_VALUE',

  // Submissions
  UPDATE_SUBMISSION_TOKEN = 'UPDATE_SUBMISSION_TOKEN',
  UPDATE_DELIVERY_ROUTE_INFORMATION = 'UPDATE_DELIVERY_ROUTE_INFORMATION',
  CLEAR_DELIVERY_ROUTE_INFORMATION = 'CLEAR_DELIVERY_ROUTE_INFORMATION',

  // Submission Statuses
  FLAG_REQUEST_MADE = 'FLAG_REQUEST_MADE',
  FLAG_AS_IN_PROGRESS = 'FLAG_AS_IN_PROGRESS',
  FLAG_AS_FAILURE = 'FLAG_AS_FAILURE',
  FLAG_AS_SUCCESS = 'FLAG_AS_SUCCESS',
  FLAG_SERVER_ERROR = 'FLAG_SERVER_ERROR',
  CLEAR_STATUSES = 'CLEAR_STATUSES',

}