export enum actionTypes {
  // Google Maps API & Autocomplete
  LOAD_GOOGLE_PLACES_API = 'LOAD_GOOGLE_PLACES_API',
  FETCH_AUTOCOMPLETE = 'FETCH_AUTOCOMPLETE',
  UPDATE_PREDICTIONS = 'UPDATE_PREDICTIONS',
  CLEAR_PREDICTIONS = 'CLEAR_PREDICTIONS',

}